name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - feature/CI

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.11.0'

      # Get dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Build web
      - name: Build Flutter Web
        run: flutter build web --release \
             --dart-define=API_BASE_URL=https://dishlabstageapi.azurewebsites.net \
             --dart-define=ENV=stage

      # Deploy to Azure
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DISHLAB_STAGE_22424 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build/web"